/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface article {
  content?: string;
  id: string;
  link: string;
  title: string;
}
